Check VERSION
Check version for avoiding Exception in method isIgnoringBatteryOptimizations(String packageName). Without this, causes NoSuchMethodError.